name: 'API docs generator'
description:
  'Generate OpenAPI and markdown API documentation based on routes files.'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  routesPaths:
    description: 'Your input description here'
    required: true
    default: ''

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
